Add the Telemetry container:
This adds configuration to build a container with Ceilometer and Aodh. It's
basically our old Ceilometer config ported to Mitaka with Aodh replacing the
part responsible for managing alarms.
A few things to be aware of:

1. This use our old `pipeline` files, which are very default ones. We need to:
 a) customise them for our needs
 b) puppetise them (some work on this has been done upstream on this, but it's
    still WIP)
2. The number of workers is set to some arbitrary values and may need
   adjusting.
3. TTLs for meters, samples and alarms was set based on what we have now in
   Production, but can be changed later.
4. The expirer (responsible for enforcing TTLs) doesn't seem to be happy with
   only the built-in `cron` resource and as a result this error is displayed:
   ```
   Error: Could not find a suitable provider for cron
   ```
   hence addition of the custom module.
5. Aodh is pinned to 'stable/newton' because of a change in master that has
   broken compatibility for older revisions:
   https://github.com/openstack/puppet-aodh/commit/093eeb5ecf9fcd44c3f55c5e0ec1195b1f218d0b
   The Mitaka branch installs `python-pymemcache` instead of `python-memcache`
   thus effectively requiring the module to be referred by a different name:
   ```
   >>> import memcache
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
   ImportError: No module named memcache
   >>> import pymemcache
   >>>
   ```
6. The Puppet module for Aodh is using the Newton branch due to some files
   being moved somewhere else for Ocata. After this deployment is done, I'll
   look into switching to master.

There are some broader consideration we need to discuss in the future, but for
now I want to push this initial version so we have this service containerized.

I'm open to any questions and/or suggestion. More testing also appreciated.